server:
  port: 8080
  servlet:
    context-path: /black-hole


spring:
  profiles:
    active: @spring.profiles.active@
  #    active: home
  #    active: company
  #    active: preview
  #    active: test
  #    active: production
  application:
    name: trace-source
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid: #以下是支持的全局默认值
        initial-size:
        max-active:
        min-idle:
        max-wait:
        time-between-eviction-runs-millis:
        time-between-log-stats-millis:
        stat-sqlmax-size:
        min-evictable-idle-time-millis:
        max-evictable-idle-time-millis:
        test-while-idle:
        test-on-borrow:
        test-on-return:
        validation-query:
        validation-query-timeout:
        use-global-datasource-stat:
        async-init:
        clear-filters-enable:
        reset-stat-enable:
        not-full-timeout-retry-count:
        max-wait-thread-count:
        fail-fast:
        phyTimeout-millis:
        keep-alive:
        pool-prepared-statements:
        init-variants:
        init-global-variants:
        use-unfair-lock:
        kill-when-socket-read-timeout:
        connection-properties:
        max-pool-prepared-statement-per-connection-size:
        init-connection-sqls:
        share-prepared-statements:
        connection-errorretry-attempts:
        break-after-acquire-failure:
        filters: stat,wall # 注意这个值和druid原生不一致，默认启动了stat,wall
        wall:
          noneBaseStatementAllow:
          callAllow:
          selectAllow:
          selectIntoAllow:
          selectIntoOutfileAllow:
          selectWhereAlwayTrueCheck:
          selectHavingAlwayTrueCheck:
          selectUnionCheck:
          selectMinusCheck:
          selectExceptCheck:
          selectIntersectCheck:
          createTableAllow:
          dropTableAllow:
          alterTableAllow:
          renameTableAllow:
          hintAllow:
          lockTableAllow:
          startTransactionAllow:
          blockAllow:
          conditionAndAlwayTrueAllow:
          conditionAndAlwayFalseAllow:
          conditionDoubleConstAllow:
          conditionLikeTrueAllow:
          selectAllColumnAllow:
          deleteAllow:
          deleteWhereAlwayTrueCheck:
          deleteWhereNoneCheck:
          updateAllow:
          updateWhereAlayTrueCheck:
          updateWhereNoneCheck:
          insertAllow:
          mergeAllow:
          minusAllow:
          intersectAllow:
          replaceAllow:
          setAllow:
          commitAllow:
          rollbackAllow:
          useAllow:
          multiStatementAllow:
          truncateAllow:
          commentAllow:
          strictSyntaxCheck:
          constArithmeticAllow:
          limitZeroAllow:
          describeAllow:
          showAllow:
          schemaCheck:
          tableCheck:
          functionCheck:
          objectCheck:
          variantCheck:
          mustParameterized:
          doPrivilegedAllow:
          dir:
          tenantTablePattern:
          tenantColumn:
          wrapAllow:
          metadataAllow:
          conditionOpXorAllow:
          conditionOpBitwseAllow:
          caseConditionConstAllow:
          completeInsertValuesCheck:
          insertValuesCheckSize:
          selectLimit:
        stat:
          merge-sql:
          log-slow-sql:
          slow-sql-millis:
    #      datasource:
    #        master:
    #          username: root
    #          password: 123456
    #          driver-class-name: com.mysql.jdbc.Driver
    #          url: jdbc:mysql://xx.xx.xx.xx:3306/dynamic?characterEncoding=utf8&useSSL=false
    #          druid: # 以下是独立参数，每个库可以重新设置
    #            initial-size:
    #            validation-query: select 1 FROM DUAL #比如oracle就需要重新设置这个
    #            public-key: #（非全局参数）设置即表示启用加密,底层会自动帮你配置相关的连接参数和filter，推荐使用本项目自带的加密方法。
    #           ......

    # 生成 publickey 和密码，推荐使用本项目自带的加密方法。
    # java -cp druid-1.1.10.jar com.alibaba.druid.filter.config.ConfigTools youpassword











